apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.36
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "Mysql123!"
    - name: MYSQL_DATABASE
      value: "main_db"
    - name: MYSQL_USER
      value: "root"
    - name: MYSQL_PASSWORD
      value: "Mysql123!"
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None # Headless Service (Opsiyonel)
