apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: nodejs-img
        ports:
        - containerPort: 8001
        env:
        - name: DB_HOST
          value: "mysql-service" # MySQL Service adı
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Mysql123!"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
  type: LoadBalancer
